# Generated by Django 5.0.6 on 2024-06-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ModelApi", "0002_reqmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("BlogTitle", models.TextField(default="")),
                ("BlogDiscription", models.TextField(default="")),
                ("Photo", models.TextField(default="")),
                ("Video", models.TextField(default="")),
            ],
        ),
        migrations.CreateModel(
            name="FeedbackForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Patientname", models.TextField(default="")),
                ("Mobileno", models.TextField(default="")),
                ("Disease", models.TextField(default="")),
            ],
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Video", models.TextField(default="")),
            ],
        ),
    ]
